version: "3.8"

services:
  itn-edunusa-paud-kanzul-khairat-fe-development:
    image: itn-edunusa-paud-kanzul-khairat-fe-development:latest
    container_name: itn-edunusa-paud-kanzul-khairat-fe-development
    build:
      context: .
      dockerfile: docker/Dockerfile.development
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    ports:
      - "3501:6006"
    restart: unless-stopped
    env_file:
      - env/.env.development