version: "3.8"

services:
  itn-edunusa-paud-kanzul-khairat-fe-development:
    image: itn-edunusa-paud-kanzul-khairat-fe-development-img:latest
    container_name: itn-edunusa-paud-kanzul-khairat-fe-development-ctr
    build:
      context: ../
      dockerfile: composer/docker/Dockerfile.development
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    ports:
      - "127.0.0.1:3501:6006"
    restart: unless-stopped
    env_file:
      - env/development/.env

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-development.rule=Host(`development-paud-kanzul-khairat-presensi.edunusa.co.id`)"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-development.entrypoints=websecure"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-development.tls=true"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-development.tls.certresolver=mytlschallenge"
      - "traefik.http.services.itn-edunusa-paud-kanzul-khairat-fe-development.loadbalancer.server.port=6006"
      # (jika backend kamu pakai prefix API seperti /api atau /graphql)
      # - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-development.middlewares=strip-prefix"
      # - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"

networks:
  traefik:
    external: true
