version: "3.8"

services:
  itn-edunusa-paud-kanzul-khairat-fe-production:
    image: itn-edunusa-paud-kanzul-khairat-fe-production-img:latest
    container_name: itn-edunusa-paud-kanzul-khairat-fe-production-ctr
    build:
      context: ../
      dockerfile: composer/docker/Dockerfile.production
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    ports:
      - "127.0.0.1:3505:6006"
    restart: unless-stopped
    env_file:
      - env/production/.env

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-production.rule=Host(`paud-kanzul-khairat-presensi.edunusa.co.id`)"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-production.entrypoints=websecure"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-production.tls=true"
      - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-production.tls.certresolver=mytlschallenge"
      - "traefik.http.services.itn-edunusa-paud-kanzul-khairat-fe-production.loadbalancer.server.port=6006"
      # (jika backend kamu pakai prefix API seperti /api atau /graphql)
      # - "traefik.http.routers.itn-edunusa-paud-kanzul-khairat-fe-production.middlewares=strip-prefix"
      # - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"

networks:
  traefik:
    external: true
