# =====================
# BUILD STAGE
# =====================
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG NODE_ENV
ARG NEXT_PUBLIC_API_URL
ARG NEXT_TELEMETRY_DISABLED

ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

RUN npm run build

# =====================
# RUNTIME STAGE
# =====================
FROM node:18-alpine AS runner
WORKDIR /app

# timezone
RUN apk add --no-cache tzdata \
 && cp /usr/share/zoneinfo/Asia/Makassar /etc/localtime \
 && echo "Asia/Makassar" > /etc/timezone

# non-root user
RUN addgroup -S nodejs -g 1001 \
 && adduser -S nextjs -u 1001

# copy app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.* ./

# fix ownership
RUN chown -R nextjs:nodejs /app

USER nextjs
ENV NODE_ENV=production

CMD ["node", "node_modules/next/dist/bin/next", "start", "-p", "6006"]
