# ======================
# 1. Builder
# ======================
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG NODE_ENV=production
ARG NEXT_PUBLIC_API_URL
ARG NEXT_TELEMETRY_DISABLED

ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

RUN npm run build


# ======================
# 2. Runner
# ======================
FROM node:18-alpine AS runner
WORKDIR /app

# timezone
RUN apk add --no-cache tzdata \
 && cp /usr/share/zoneinfo/Asia/Makassar /etc/localtime \
 && echo "Asia/Makassar" > /etc/timezone

# non-root user
RUN addgroup -g 1001 nodejs \
 && adduser -D -u 1001 -G nodejs nextjs

# copy ONLY standalone output
COPY --chown=nextjs:nodejs --from=builder /app/.next/standalone ./
COPY --chown=nextjs:nodejs --from=builder /app/.next/static ./.next/static
COPY --chown=nextjs:nodejs --from=builder /app/public ./public

USER nextjs

EXPOSE 6006
CMD ["node", "server.js"]
